[project]
name = "thrift-walk-web"
revision = "1.0"

[providers]
env = "env://"
dotenv = "dotenv://"

[profiles.development]
POSTGRES_USER = { description = "Postgres Username", default = "postgres" }
POSTGRES_PASSWORD = { description = "Postgres Password", default = "db-password" }
POSTGRES_DB = { description = "Postgres Database", default = "postgres" }
DATABASE_URL = { description = "Database connection string", default = "postgresql://postgres:db-password@localhost:5432/postgres?schema=public" }

BETTER_AUTH_URL = { description = "BetterAuth URL", default = "http://localhost:3000" }
BETTER_AUTH_SECRET = { description = "BetterAuth secret", required = true, type = "base64", generate = { bytes = 64 }, providers = [
    "dotenv",
] }

# GOOGLE_CLIENT_ID = { description = "Google OAuth client ID", required = true, providers = [
#     "dotenv",
# ] }
# GOOGLE_CLIENT_SECRET = { description = "Google OAuth client secret", required = true, providers = [
#     "dotenv",
# ] }

[profiles.production]
POSTGRES_PASSWORD = { description = "Postgres Password", required = true }
DATABASE_URL = { description = "Database connection string", required = true }
BETTER_AUTH_URL = { description = "BetterAuth URL", required = true }
BETTER_AUTH_SECRET = { description = "BetterAuth secret", required = true }
# GOOGLE_CLIENT_ID = { description = "Google OAuth client ID", required = true }
# GOOGLE_CLIENT_SECRET = { description = "Google OAuth client secret", required = true }
