//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import type {
    AggregateArgs as $AggregateArgs,
    CheckedCreateInput as $CheckedCreateInput,
    CheckedUpdateInput as $CheckedUpdateInput,
    CountArgs as $CountArgs,
    CreateArgs as $CreateArgs,
    CreateManyAndReturnArgs as $CreateManyAndReturnArgs,
    CreateManyArgs as $CreateManyArgs,
    DeleteArgs as $DeleteArgs,
    DeleteManyArgs as $DeleteManyArgs,
    ExistsArgs as $ExistsArgs,
    FindFirstArgs as $FindFirstArgs,
    FindManyArgs as $FindManyArgs,
    FindUniqueArgs as $FindUniqueArgs,
    GroupByArgs as $GroupByArgs,
    IncludeInput as $IncludeInput,
    OmitInput as $OmitInput,
    QueryOptions as $QueryOptions,
    SimplifiedPlainResult as $Result,
    SelectIncludeOmit as $SelectIncludeOmit,
    SelectInput as $SelectInput,
    UncheckedCreateInput as $UncheckedCreateInput,
    UncheckedUpdateInput as $UncheckedUpdateInput,
    UpdateArgs as $UpdateArgs,
    UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs,
    UpdateManyArgs as $UpdateManyArgs,
    UpsertArgs as $UpsertArgs,
    WhereInput as $WhereInput,
} from "@zenstackhq/orm";

import type { SchemaType as $Schema } from "./schema";
export type UserFindManyArgs = $FindManyArgs<$Schema, "User">;
export type UserFindUniqueArgs = $FindUniqueArgs<$Schema, "User">;
export type UserFindFirstArgs = $FindFirstArgs<$Schema, "User">;
export type UserExistsArgs = $ExistsArgs<$Schema, "User">;
export type UserCreateArgs = $CreateArgs<$Schema, "User">;
export type UserCreateManyArgs = $CreateManyArgs<$Schema, "User">;
export type UserCreateManyAndReturnArgs = $CreateManyAndReturnArgs<
    $Schema,
    "User"
>;
export type UserUpdateArgs = $UpdateArgs<$Schema, "User">;
export type UserUpdateManyArgs = $UpdateManyArgs<$Schema, "User">;
export type UserUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<
    $Schema,
    "User"
>;
export type UserUpsertArgs = $UpsertArgs<$Schema, "User">;
export type UserDeleteArgs = $DeleteArgs<$Schema, "User">;
export type UserDeleteManyArgs = $DeleteManyArgs<$Schema, "User">;
export type UserCountArgs = $CountArgs<$Schema, "User">;
export type UserAggregateArgs = $AggregateArgs<$Schema, "User">;
export type UserGroupByArgs = $GroupByArgs<$Schema, "User">;
export type UserWhereInput = $WhereInput<$Schema, "User">;
export type UserSelect = $SelectInput<$Schema, "User">;
export type UserInclude = $IncludeInput<$Schema, "User">;
export type UserOmit = $OmitInput<$Schema, "User">;
export type UserUncheckedCreateInput = $UncheckedCreateInput<$Schema, "User">;
export type UserCheckedCreateInput = $CheckedCreateInput<$Schema, "User">;
export type UserUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, "User">;
export type UserCheckedUpdateInput = $CheckedUpdateInput<$Schema, "User">;
export type UserGetPayload<
    Args extends $SelectIncludeOmit<$Schema, "User", true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, "User", Args, Options>;
