//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import type {
    AggregateArgs as $AggregateArgs,
    CheckedCreateInput as $CheckedCreateInput,
    CheckedUpdateInput as $CheckedUpdateInput,
    CountArgs as $CountArgs,
    CreateArgs as $CreateArgs,
    CreateManyAndReturnArgs as $CreateManyAndReturnArgs,
    CreateManyArgs as $CreateManyArgs,
    DeleteArgs as $DeleteArgs,
    DeleteManyArgs as $DeleteManyArgs,
    ExistsArgs as $ExistsArgs,
    FindFirstArgs as $FindFirstArgs,
    FindManyArgs as $FindManyArgs,
    FindUniqueArgs as $FindUniqueArgs,
    GroupByArgs as $GroupByArgs,
    IncludeInput as $IncludeInput,
    OmitInput as $OmitInput,
    QueryOptions as $QueryOptions,
    SimplifiedPlainResult as $Result,
    SelectIncludeOmit as $SelectIncludeOmit,
    SelectInput as $SelectInput,
    UncheckedCreateInput as $UncheckedCreateInput,
    UncheckedUpdateInput as $UncheckedUpdateInput,
    UpdateArgs as $UpdateArgs,
    UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs,
    UpdateManyArgs as $UpdateManyArgs,
    UpsertArgs as $UpsertArgs,
    WhereInput as $WhereInput,
} from "@zenstackhq/orm";

import type { SchemaType as $Schema } from "./schema";
export type UserFindManyArgs = $FindManyArgs<$Schema, "User">;
export type UserFindUniqueArgs = $FindUniqueArgs<$Schema, "User">;
export type UserFindFirstArgs = $FindFirstArgs<$Schema, "User">;
export type UserExistsArgs = $ExistsArgs<$Schema, "User">;
export type UserCreateArgs = $CreateArgs<$Schema, "User">;
export type UserCreateManyArgs = $CreateManyArgs<$Schema, "User">;
export type UserCreateManyAndReturnArgs = $CreateManyAndReturnArgs<
    $Schema,
    "User"
>;
export type UserUpdateArgs = $UpdateArgs<$Schema, "User">;
export type UserUpdateManyArgs = $UpdateManyArgs<$Schema, "User">;
export type UserUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<
    $Schema,
    "User"
>;
export type UserUpsertArgs = $UpsertArgs<$Schema, "User">;
export type UserDeleteArgs = $DeleteArgs<$Schema, "User">;
export type UserDeleteManyArgs = $DeleteManyArgs<$Schema, "User">;
export type UserCountArgs = $CountArgs<$Schema, "User">;
export type UserAggregateArgs = $AggregateArgs<$Schema, "User">;
export type UserGroupByArgs = $GroupByArgs<$Schema, "User">;
export type UserWhereInput = $WhereInput<$Schema, "User">;
export type UserSelect = $SelectInput<$Schema, "User">;
export type UserInclude = $IncludeInput<$Schema, "User">;
export type UserOmit = $OmitInput<$Schema, "User">;
export type UserUncheckedCreateInput = $UncheckedCreateInput<$Schema, "User">;
export type UserCheckedCreateInput = $CheckedCreateInput<$Schema, "User">;
export type UserUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, "User">;
export type UserCheckedUpdateInput = $CheckedUpdateInput<$Schema, "User">;
export type UserGetPayload<
    Args extends $SelectIncludeOmit<$Schema, "User", true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, "User", Args, Options>;
export type SessionFindManyArgs = $FindManyArgs<$Schema, "Session">;
export type SessionFindUniqueArgs = $FindUniqueArgs<$Schema, "Session">;
export type SessionFindFirstArgs = $FindFirstArgs<$Schema, "Session">;
export type SessionExistsArgs = $ExistsArgs<$Schema, "Session">;
export type SessionCreateArgs = $CreateArgs<$Schema, "Session">;
export type SessionCreateManyArgs = $CreateManyArgs<$Schema, "Session">;
export type SessionCreateManyAndReturnArgs = $CreateManyAndReturnArgs<
    $Schema,
    "Session"
>;
export type SessionUpdateArgs = $UpdateArgs<$Schema, "Session">;
export type SessionUpdateManyArgs = $UpdateManyArgs<$Schema, "Session">;
export type SessionUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<
    $Schema,
    "Session"
>;
export type SessionUpsertArgs = $UpsertArgs<$Schema, "Session">;
export type SessionDeleteArgs = $DeleteArgs<$Schema, "Session">;
export type SessionDeleteManyArgs = $DeleteManyArgs<$Schema, "Session">;
export type SessionCountArgs = $CountArgs<$Schema, "Session">;
export type SessionAggregateArgs = $AggregateArgs<$Schema, "Session">;
export type SessionGroupByArgs = $GroupByArgs<$Schema, "Session">;
export type SessionWhereInput = $WhereInput<$Schema, "Session">;
export type SessionSelect = $SelectInput<$Schema, "Session">;
export type SessionInclude = $IncludeInput<$Schema, "Session">;
export type SessionOmit = $OmitInput<$Schema, "Session">;
export type SessionUncheckedCreateInput = $UncheckedCreateInput<
    $Schema,
    "Session"
>;
export type SessionCheckedCreateInput = $CheckedCreateInput<$Schema, "Session">;
export type SessionUncheckedUpdateInput = $UncheckedUpdateInput<
    $Schema,
    "Session"
>;
export type SessionCheckedUpdateInput = $CheckedUpdateInput<$Schema, "Session">;
export type SessionGetPayload<
    Args extends $SelectIncludeOmit<$Schema, "Session", true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, "Session", Args, Options>;
export type AccountFindManyArgs = $FindManyArgs<$Schema, "Account">;
export type AccountFindUniqueArgs = $FindUniqueArgs<$Schema, "Account">;
export type AccountFindFirstArgs = $FindFirstArgs<$Schema, "Account">;
export type AccountExistsArgs = $ExistsArgs<$Schema, "Account">;
export type AccountCreateArgs = $CreateArgs<$Schema, "Account">;
export type AccountCreateManyArgs = $CreateManyArgs<$Schema, "Account">;
export type AccountCreateManyAndReturnArgs = $CreateManyAndReturnArgs<
    $Schema,
    "Account"
>;
export type AccountUpdateArgs = $UpdateArgs<$Schema, "Account">;
export type AccountUpdateManyArgs = $UpdateManyArgs<$Schema, "Account">;
export type AccountUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<
    $Schema,
    "Account"
>;
export type AccountUpsertArgs = $UpsertArgs<$Schema, "Account">;
export type AccountDeleteArgs = $DeleteArgs<$Schema, "Account">;
export type AccountDeleteManyArgs = $DeleteManyArgs<$Schema, "Account">;
export type AccountCountArgs = $CountArgs<$Schema, "Account">;
export type AccountAggregateArgs = $AggregateArgs<$Schema, "Account">;
export type AccountGroupByArgs = $GroupByArgs<$Schema, "Account">;
export type AccountWhereInput = $WhereInput<$Schema, "Account">;
export type AccountSelect = $SelectInput<$Schema, "Account">;
export type AccountInclude = $IncludeInput<$Schema, "Account">;
export type AccountOmit = $OmitInput<$Schema, "Account">;
export type AccountUncheckedCreateInput = $UncheckedCreateInput<
    $Schema,
    "Account"
>;
export type AccountCheckedCreateInput = $CheckedCreateInput<$Schema, "Account">;
export type AccountUncheckedUpdateInput = $UncheckedUpdateInput<
    $Schema,
    "Account"
>;
export type AccountCheckedUpdateInput = $CheckedUpdateInput<$Schema, "Account">;
export type AccountGetPayload<
    Args extends $SelectIncludeOmit<$Schema, "Account", true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, "Account", Args, Options>;
export type VerificationFindManyArgs = $FindManyArgs<$Schema, "Verification">;
export type VerificationFindUniqueArgs = $FindUniqueArgs<
    $Schema,
    "Verification"
>;
export type VerificationFindFirstArgs = $FindFirstArgs<$Schema, "Verification">;
export type VerificationExistsArgs = $ExistsArgs<$Schema, "Verification">;
export type VerificationCreateArgs = $CreateArgs<$Schema, "Verification">;
export type VerificationCreateManyArgs = $CreateManyArgs<
    $Schema,
    "Verification"
>;
export type VerificationCreateManyAndReturnArgs = $CreateManyAndReturnArgs<
    $Schema,
    "Verification"
>;
export type VerificationUpdateArgs = $UpdateArgs<$Schema, "Verification">;
export type VerificationUpdateManyArgs = $UpdateManyArgs<
    $Schema,
    "Verification"
>;
export type VerificationUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<
    $Schema,
    "Verification"
>;
export type VerificationUpsertArgs = $UpsertArgs<$Schema, "Verification">;
export type VerificationDeleteArgs = $DeleteArgs<$Schema, "Verification">;
export type VerificationDeleteManyArgs = $DeleteManyArgs<
    $Schema,
    "Verification"
>;
export type VerificationCountArgs = $CountArgs<$Schema, "Verification">;
export type VerificationAggregateArgs = $AggregateArgs<$Schema, "Verification">;
export type VerificationGroupByArgs = $GroupByArgs<$Schema, "Verification">;
export type VerificationWhereInput = $WhereInput<$Schema, "Verification">;
export type VerificationSelect = $SelectInput<$Schema, "Verification">;
export type VerificationInclude = $IncludeInput<$Schema, "Verification">;
export type VerificationOmit = $OmitInput<$Schema, "Verification">;
export type VerificationUncheckedCreateInput = $UncheckedCreateInput<
    $Schema,
    "Verification"
>;
export type VerificationCheckedCreateInput = $CheckedCreateInput<
    $Schema,
    "Verification"
>;
export type VerificationUncheckedUpdateInput = $UncheckedUpdateInput<
    $Schema,
    "Verification"
>;
export type VerificationCheckedUpdateInput = $CheckedUpdateInput<
    $Schema,
    "Verification"
>;
export type VerificationGetPayload<
    Args extends $SelectIncludeOmit<$Schema, "Verification", true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, "Verification", Args, Options>;
