//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import type { ModelResult as $ModelResult } from "@zenstackhq/orm";

import type { SchemaType as $Schema } from "./schema";
export type User = $ModelResult<$Schema, "User">;
