//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import {
    type AttributeApplication,
    ExpressionUtils,
    type FieldDefault,
    type SchemaDef,
} from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql",
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [
                        { name: "@id" },
                        {
                            name: "@default",
                            args: [
                                {
                                    name: "value",
                                    value: ExpressionUtils.call("cuid"),
                                },
                            ],
                        },
                    ] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault,
                },
                name: {
                    name: "name",
                    type: "String",
                },
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
            },
        },
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
